# Generated by Django 3.2.1 on 2021-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210511_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirationDateMonth',
            field=models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirationDateYear',
            field=models.PositiveSmallIntegerField(choices=[(21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=22),
        ),
    ]
