# Generated by Django 3.2.1 on 2021-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='postalCode',
            field=models.PositiveBigIntegerField(),
        ),
    ]
