# Generated by Django 3.2.1 on 2021-05-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_contact_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
        ),
    ]
