# Generated by Django 3.2.1 on 2021-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210514_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
