# Generated by Django 3.2.1 on 2021-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='url',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
