# Generated by Django 3.2.1 on 2021-05-07 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subclass',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='superclass',
            field=models.CharField(default='cereal', max_length=255),
            preserve_default=False,
        ),
    ]
